export const bulgarianPhoneticLUT = {
    // Number row
    Backquote: ["§", "±"], // Backquote (usually under Esc)
    "Digit1": ["1", "!"],
    "Digit2": ["2", "@"],
    "Digit3": ["3", "№"],
    "Digit4": ["4", '$'],
    "Digit5": ["5", "%"],
    "Digit6": ["6", "€"],
    "Digit7": ["7", "§"],
    "Digit8": ["8", "*"],
    "Digit9": ["9", "("],
    "Digit0": ["0", ")"],
    Minus: ["-", "_"],
    Equal: ["=", "+"],

    KeyQ: ["ч", "Ч"],
    KeyW: ["ш", "Ш"],
    KeyE: ["е", "Е"],
    KeyR: ["р", "Р"],
    KeyT: ["т", "Т"],
    KeyY: ["ъ", "Ъ"],
    KeyU: ["у", "У"],
    KeyI: ["и", "И"],
    KeyO: ["о", "О"],
    KeyP: ["п", "П"],
    BracketLeft: ["я", "Я"],
    BracketRight: ["щ", "Щ"],

    KeyA: ["а", "А"],
    KeyS: ["с", "С"],
    KeyD: ["д", "Д"],
    KeyF: ["ф", "Ф"],
    KeyG: ["г", "Г"],
    KeyH: ["х", "Х"],
    KeyJ: ["й", "Й"],
    KeyK: ["к", "К"],
    KeyL: ["л", "Л"],
    Semicolon: [";", ":"],
    Quote: ["'", '"'],
    Backslash: ["\\", "|"],

    IntlBackslash: ["ю", "Ю"], // International backslash key, often used for the Bulgarian 'ѝ'
    KeyZ: ["з", "З"],
    KeyX: ["ж", "Ж"],
    KeyC: ["ц", "Ц"],
    KeyV: ["в", "В"],
    KeyB: ["б", "Б"],
    KeyN: ["н", "Н"],
    KeyM: ["м", "М"],
    Comma: [",", "<"], // Sometimes mapped to "ю" as well
    Period: [".", ">"],
    Slash: ["/", "?"],
} as {[key: string]: [string, string]};